# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://c-ffi.{default}/":
    type: upstream
    upstream: "c:http"

"https://rust-ffi.{default}/":
    type: upstream
    upstream: "rust:http"
